/*
 * {{ slug }}.exe - Launcher stub generated by snackbox
 * Console mode: {{ console_mode }}
 *
 * Compile (MinGW):
 *   windres launcher.rc -O coff -o launcher.res
 *   gcc -static -O2 {{ "-mconsole" if console_mode == "yes" else "-mwindows" }} -o {{ slug }}.exe launcher.c launcher.res
 */
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

{% if console_mode == "attach" %}
static int should_keep_console(void) {
    HWND console_wnd = GetConsoleWindow();
    if (!console_wnd) return 0;

    DWORD console_pid = 0;
    GetWindowThreadProcessId(console_wnd, &console_pid);

    /* If we don't own the console, we're running from a terminal - keep it */
    return (console_pid != GetCurrentProcessId());
}
{% endif %}

int {% if console_mode == "no" %}WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow){% else %}main(int argc, char *argv[]){% endif %} {
{% if console_mode == "attach" %}
    int from_terminal = should_keep_console();

    /* If we own the console (launched from Explorer), free it */
    if (!from_terminal) {
        FreeConsole();
    }
{% endif %}

    /* Get directory where this exe lives */
    char exe_dir[MAX_PATH];
    GetModuleFileNameA(NULL, exe_dir, MAX_PATH);
    char *last_sep = strrchr(exe_dir, '\\');
    if (last_sep) *last_sep = '\0';

    /* Build python executable path */
    char python_exe[MAX_PATH];
    snprintf(python_exe, sizeof(python_exe), "%s\\python\\python.exe", exe_dir);

    /* Build command line */
    char cmd[8192];
    char *p = cmd;
    p += snprintf(p, sizeof(cmd), "\"%s\" -m {{ entry_point }}", python_exe);

{% if console_mode == "attach" %}
    /* Pass --console flag if running from terminal */
    if (from_terminal) {
        p += snprintf(p, cmd + sizeof(cmd) - p, " --console");
    }
{% endif %}

{% if console_mode == "no" %}
    /* Forward command line arguments (GUI mode) */
    if (lpCmdLine && *lpCmdLine) {
        p += snprintf(p, cmd + sizeof(cmd) - p, " %s", lpCmdLine);
    }
{% else %}
    /* Forward command line arguments */
    for (int i = 1; i < argc; i++) {
        if (strchr(argv[i], ' ') || strchr(argv[i], '"')) {
            p += snprintf(p, cmd + sizeof(cmd) - p, " \"%s\"", argv[i]);
        } else {
            p += snprintf(p, cmd + sizeof(cmd) - p, " %s", argv[i]);
        }
    }
{% endif %}

{% if env_vars %}
    /* Set environment variables */
{% for key, value in env_vars.items() %}
    SetEnvironmentVariableA("{{ key }}", "{{ value }}");
{% endfor %}
{% endif %}

    /* Launch Python */
    STARTUPINFOA si = {0};
    PROCESS_INFORMATION pi = {0};
    si.cb = sizeof(si);

{% if console_mode == "attach" %}
    DWORD flags = from_terminal ? 0 : CREATE_NO_WINDOW;
{% elif console_mode == "no" %}
    DWORD flags = CREATE_NO_WINDOW;
{% else %}
    DWORD flags = 0;
{% endif %}

    BOOL success = CreateProcessA(
        python_exe,
        cmd,
        NULL, NULL,
        {% if console_mode == "yes" %}TRUE{% else %}FALSE{% endif %},  /* Inherit handles */
        flags,
        NULL,
        exe_dir,
        &si, &pi
    );

    if (!success) {
{% if console_mode == "yes" %}
        fprintf(stderr, "Failed to start Python (error %lu)\n", GetLastError());
{% else %}
        char err_msg[256];
        snprintf(err_msg, sizeof(err_msg), "Failed to start Python (error %lu)", GetLastError());
        MessageBoxA(NULL, err_msg, "{{ slug }}", MB_OK | MB_ICONERROR);
{% endif %}
        return 1;
    }

    WaitForSingleObject(pi.hProcess, INFINITE);

    DWORD exit_code = 1;
    GetExitCodeProcess(pi.hProcess, &exit_code);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);

    return (int)exit_code;
}
